version: 3

volumes:
  mongo: {}

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    image: mongo:latest
