version: "3"

volumes:
  mongo: {}

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    image:
      mongo:latest

  imgtagger:
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
    ports:
      - '9090:8080'
    image:
      imgtagger:latest
    build:
      context: .


